pipeline:
  name: test_gh_nodejs-goof
  identifier: test_gh_nodejsgoof
  projectIdentifier: testal
  orgIdentifier: TPMLabs
  tags:
    first: ""
  properties:
    ci:
      codebase:
        connectorRef: test_al
        repoName: nodejs-goof
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        template:
          templateRef: owasp_snyk
          versionLabel: test
