pipeline:
  name: test_gh_nodejs-goof
  identifier: test_gh_nodejsgoof
  projectIdentifier: testal
  orgIdentifier: TPMLabs
  tags:
    first: ""
  properties:
    ci:
      codebase:
        connectorRef: test_al
        repoName: nodejs-goof
        build: <+input>
  stages:
    - stage:
        name: test_node
        identifier: test_node
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          sharedPaths:
            - /var/run
          execution:
            steps:
              - parallel:
                  - step:
                      type: Background
                      name: dind
                      identifier: dind
                      spec:
                        connectorRef: account.harnessImage
                        image: docker:dind
                        shell: Sh
                  - step:
                      type: AquaTrivy
                      name: AquaTrivy_1
                      identifier: AquaTrivy_1
                      spec:
                        target:
                          detection: auto
                          type: container
                        advanced:
                          log:
                            level: info
                          args:
                            cli: ""
                        privileged: true
                        mode: orchestration
                        config: default
                        image:
                          type: local_image
                          name: alsharma9/juice-shop
                          tag: latest
                        resources:
                          limits:
                            memory: 2G
                            cpu: 1000m
                  - step:
                      type: Grype
                      name: Grype_1
                      identifier: Grype_1
                      spec:
                        target:
                          detection: auto
                          type: container
                        advanced:
                          log:
                            level: info
                          args:
                            cli: ""
                        privileged: true
                        mode: orchestration
                        config: default
                        image:
                          type: local_image
                          name: alsharma9/juice-shop
                          tag: latest
                        resources:
                          limits:
                            memory: 2G
                            cpu: 1000m
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: rancher_local
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        delegateSelectors:
          - terraform-delegate
