pipeline:
  identifier: Build_kunalnano_nodejs_goof_1720712549588
  name: Snyk Scan Pipeline
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1720712151481
        repoName: kunalnano/nodejs-goof
        branch: main
        build: <+input>
  stages:
    - stage:
        identifier: snyk_scan_stage
        name: Snyk Scan
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: snykAuthAndTest
                  name: Snyk Auth and Test
                  type: Run
                  spec:
                    connectorRef: account.harnessImage
                    image: node:18
                    shell: Sh
                    envVariables:
                      SNYK_TOKEN: <+secrets.getValue("SNYK_TOKEN_SECRET")>
                    command: |-
                      snyk auth ${SNYK_TOKEN}  # Authenticate using the token
                      snyk test --package-manager=npm > snyk_test_npm.json || true
                  timeout: 20m
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: harnessk8srancherconnector
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              os: Linux
        variables:
          - name: SNYK_TOKEN_SECRET
            type: String
            description: ""
            required: false
            value: bf000d3f-29a1-455d-9f54-d2d93d6d112c
