pipeline:
  identifier: Build_kunalnano_nodejs_goof_1720712549588
  name: Snyk Scan Pipeline
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1720712151481
        repoName: kunalnano/nodejs-goof
        branch: main
        build: <+input>
  stages:
    - stage:
        identifier: snyk_scan_stage
        name: Snyk Scan
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: snykAuthAndTest
                  name: Snyk Auth and Test
                  type: Run
                  spec:
                    connectorRef: account.harnessImage
                    image: node:18
                    shell: Sh
                    command: |-
                      npm install -g snyk@latest --unsafe-perm  # Install Snyk globally
                      snyk auth ${SNYK_TOKEN}  # Authenticate using the token
                      snyk test --json --output=snyk_report.json || true  # Run Snyk scan and save output as JSON
                      ls -la snyk_report.json  # List the file to confirm it exists
                    envVariables:
                      SNYK_TOKEN: <+secrets.getValue("SNYK_TOKEN_SECRET")>
                  timeout: 20m
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: harnessk8srancherconnector
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
