pipeline:
  identifier: Build_kunalnano_nodejs_goof_1720712549588
  name: Build nodejs-goof
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1720712151481
        repoName: kunalnano/nodejs-goof
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    connectorRef: account.harnessImage
                    image: alsharma9/nodejs-goof
                    shell: Sh
                    command: |-
                      npm install
                      npm install -g @angular/cli
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    connectorRef: account.harnessImage
                    image: alsharma9/nodejs-goof
                    shell: Sh
                    command: |-
                      npm run test
                      npm install -g @angular/cli
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    connectorRef: account.harnessImage
                    image: alsharma9/nodejs-goof
                    shell: Sh
                    command: npm run build
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: harnessk8srancherconnector
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
